### PR TITLE
Allow processing classes with ASM8/ASM9

### PR DESCRIPTION
**Pull request by cdegroc**
This should allow processing classes built with Java 14 (ASM8) and 17 (ASM9).

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by cdegroc** [comment]
@eed3si9n do you want to kick off the tests (workflow) before I merge?

**Comment by eed3si9n** [comment]
CI looks green now.

**Comment by cdegroc** [comment]
@eed3si9n are releases on demand or would you have an ETA for the next release?
When merged, I'll open a PR to bump up jarjar in `sbt-assembly`.

**Comment by eed3si9n** [comment]
Released https://github.com/eed3si9n/jarjar-abrams/releases/tag/v1.13.1. Should sync to Maven Central soon.

**Pull request merged**
