### PR TITLE
Add support for shading over InputStream

### PR DESCRIPTION
**Pull request by joan38**
In relation to https://github.com/lihaoyi/mill/pull/947
cc @eed3si9n @alexarchambault

### CODE REVIEW

**Comment by eed3si9n** [comment]
Looks like Travis CI is failing:

```
[info] [error] java.nio.file.DirectoryNotEmptyException: /tmp/sbt_364ea5eb/two/shadedJawn/target/scala-2.12/shaded
[info] [error] 	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:243)
[info] [error] 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[info] [error] 	at java.base/java.nio.file.Files.delete(Files.java:1141)
[info] [error] 	at com.eed3si9n.jarjarabrams.Shader$.$anonfun$shadeDirectory$3(Shader.scala:17)
[info] [error] 	at com.eed3si9n.jarjarabrams.Shader$.$anonfun$shadeDirectory$3$adapted(Shader.scala:17)
[info] [error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[info] [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[info] [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[info] [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info] [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info] [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info] [error] 	at com.eed3si9n.jarjarabrams.Shader$.shadeDirectory(Shader.scala:17)
```

You might have to delete recursively.

**Comment by joan38** [comment]
@eed3si9n I ended up replicating exactly the previous behavior by removing only files.

**Comment by joan38** [comment]
Thanks @eed3si9n. Are you planning to make a release out of this?

**Comment by eed3si9n** [comment]
Yea. Let's do it.

**Comment by eed3si9n** [comment]
Oh no did you use JDK 9+ stuff? I don't want sbt-assembly to require JDK 9+.

```
[error] /Users/eed3si9n/work/jarjar-abrams/core/src/main/scala/com/eed3si9n/jarjarabrams/Shader.scala:21:36: value readAllBytes is not a member of java.io.InputStream
[error]       Files.write(out, inputStream.readAllBytes(), StandardOpenOption.CREATE)
```

**Comment by joan38** [comment]
Yes.
Ok let me create another PR to do differently.

**Comment by joan38** [comment]
Have a look at https://github.com/eed3si9n/jarjar-abrams/pull/5

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/jarjar-abrams/releases/tag/v0.2.0 is on its way to Maven Central.

**Comment by joan38** [comment]
Nice! Thanks @eed3si9n

**Pull request merged**
